### ISSUE TITLE
Create call for speakers

### ISSUE THREAD

**Issue by helmuthb** [GDGVienna/wtmvienna-site#2]
From trello

**Comment by helmuthb** [comment]
We will create a simple google form.
There is some need for clarification from the content team: when will the detailed speaker instruction set be available? When shall the call be visible on the website?

**Comment by helmuthb** [comment]
Very first version online:
http://test.womentechmakers.at/call/

**Comment by Althaire** [comment]
Thanks @helmuthb That looks great so far! :+1: 

So after yesterday's general meeting the dates for the CFP so far are:
- *don't know the opening date*
- **Closing date:** 14th February
- **Contact applicants:** 21st February

The opening page looks really good, we should probably have a *couple of paragraphs on what kind of talks, content and speakers we're looking for as well as our goals and things like the fact that we most probably won't be covering travel and stay*. We could also include some links on writing abstracts, and tips on speaking as well. I'm personally not sure of how big the speaking community in Vienna is, but this might encourage women who have something to share to at least send in a proposal?

(*Maybe I'm loading all of us with too much responsibility but if we even went as far as sending feedback and tips instead of just rejections, we might even help curate a nice speaking community here* :sweat_smile: :sparkling_heart:  :two_hearts:  )

As for the form itself:
- Will we be displaying a little info on the speaker? If so, we need a section for that.
- This might sound a little *gooey* but maybe a "Pitch" section where the applicant has the opportunity to say why the talk is important to them and go into a little detail about it (also mention that this won't be displayed on the website). I feel like some people that give great talks sometimes have a hard time writing abstracts, so this might help to determine the speakers' passion and expression ability?

Would love opinions from everyone! Content team, maybe I'm wrong but the stuff I mentioned for the opening page would come from you? :wink:

**Comment by theRealImy** [comment]
Hi,

I agree with Pilar on all of the above.
We also talked in the last meeting a bit about this: "description of goals,
so we have local speakers, but write also that we accept international
speakers, as long as they pay flights...we can host and later on content
team will decide if the international proposal makes sense or not"
I also like the ideas of tips for speakers. @Philipp this is where you come
in.
We could instead of abstract and title just say: pitch your talk idea to
us. Be sure to mention why, what and what you are going to talk about.

> Will we be displaying a little info on the speaker? If so, we need a
> section for that

This part can be gathered after we decide on the speakers. It depends on
the content people how and when they wanna handle this.

@Philipp Angeliki - can we move forward with this and open the call soon?
You have seen we already get emails that people wanna contribute (Meral)
and it eases our work of gathering content!

Best,
Imy

On 29 December 2015 at 11:00, Pilar Huidobro <notifications@github.com>
wrote:

> Thanks @helmuthb <https://github.com/helmuthb> That looks great so far! [image:
> :+1:]
>
> So after yesterday's general meeting the dates for the CFP so far are:
>
>    - *don't know the opening date*
>    - *Closing date:* 14th February
>    - *Contact applicants:* 21st February
>
> The opening page looks really good, we should probably have a *couple of
> paragraphs on what kind of talks, content and speakers we're looking for as
> well as our goals and things like the fact that we most probably won't be
> covering travel and stay*. We could also include some links on writing
> abstracts, and tips on speaking as well. I'm personally not sure of how big
> the speaking community in Vienna is, but this might encourage women who
> have something to share to at least send in a proposal?
>
> (*Maybe I'm loading all of us with too much responsibility but if we even
> went as far as sending feedback and tips instead of just rejections, we
> might even help curate a nice speaking community here* [image:
> :sweat_smile:] [image: :sparkling_heart:] [image: :two_hearts:] )
>
> As for the form itself:
>
>    - Will we be displaying a little info on the speaker? If so, we need a
>    section for that.
>    - This might sound a little *gooey* but maybe a "Pitch" section where
>    the applicant has the opportunity to say why the talk is important to them
>    and go into a little detail about it (also mention that this won't be
>    displayed on the website). I feel like some people that give great talks
>    sometimes have a hard time writing abstracts, so this might help to
>    determine the speakers' passion and expression ability?
>
> Would love opinions from everyone! Content team, maybe I'm wrong but the
> stuff I mentioned for the opening page would come from you? [image:
> :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GDGVienna/wtmvienna-site/issues/2#issuecomment-167759312>
> .
>



-- 

*timeaturdean.com <http://timeaturdean.com>*
Technical Consultant @Semantic Web Company <https://www.semantic-web.at/>
Diversity Lead @GDGVienna <http://www.gdg-vienna.at/> & @
WomenTechmakersVienna <http://womentechmakers.at/>

**Comment by helmuthb** [comment]
Here the suggestions from @angeliki-chris https://docs.google.com/document/d/1XF95cm3kpVVSDDT4Vg0q7wcJvhZkQf2WrxsZO_P-G5o/

**Comment by helmuthb** [comment]
First implementation in 4932a3b6fb9665d60d9392702e5fdf8563b89866

**Comment by helmuthb** [comment]
Some formatting changes, link added to navigation, added section in start page
1c35fdc8c49bb298a28b90df958618b1f996c37c
