### ISSUE TITLE
Create registration

### ISSUE THREAD

**Issue by Althaire** [GDGVienna/wtmvienna-site#9]
If I'm not mistaken: Eventbrite.

Note from yesterday's meeting:
- *make more available places, count 15-20% no-show rate*
- **Registration open:** 11th of January
- **Registration deadline:** 5th March
- **8th of March:** limited number exclusive seats available for Womens’ Day
- *first 100 registrations get a goodie bag*, make it clear, so **no asking for money**

**Comment by theRealImy** [comment]
Hi! 
Can we move on with the registrations too? Tomorrow we should open the eventbrite page. 
What is needed? What is missing?

**Comment by Althaire** [comment]
I would be glad to take care of this right now. I think it would be easiest to use the same information as last year just change the dates and any details that need to be changed. Is there a WTM account I can use to login to Eventbrite and do this, or which account was used to do it last year?

**Comment by helmuthb** [comment]
This is a copy of last year's event with minimum changes required:
https://www.eventbrite.com/e/women-techmakers-vienna-2016-registration-20678720610

But we might have to remove some details as they are not yet decided, or? E.g. type of tickets, kids workshop tickets, ...

**Comment by theRealImy** [comment]
To this: we can open up only the general event tickets because we are not
sure about other workshops and content.
Question?
If we open the main event can we then later on add other workshops and so,
or do people have to register extra?
Maybe we need to open the registration at the same tie for all events we
plan to have?! Since we didn't think about this, it looks like we need to
postpone a bit the registration opening.

On 10 January 2016 at 23:59, Helmuth Breitenfellner <
notifications@github.com> wrote:

> This is a copy of last year's event with minimum changes required:
>
> https://www.eventbrite.com/e/women-techmakers-vienna-2016-registration-20678720610
>
> But we might have to remove some details as they are not yet decided, or?
> E.g. type of tickets, kids workshop tickets, ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GDGVienna/wtmvienna-site/issues/9#issuecomment-170403411>
> .
>



-- 

*timeaturdean.com <http://timeaturdean.com>*
Technical Consultant @Semantic Web Company <https://www.semantic-web.at/>
Diversity Lead @GDGVienna <http://www.gdg-vienna.at/> & @
WomenTechmakersVienna <http://womentechmakers.at/>

**Comment by helmuthb** [comment]
Registration is open and public and announced
